name: Release FOSSLight

on:
  release:
    types: [ published ]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref: [ main, develop ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.ref }}

      - name: update changelog with gren
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install github-release-notes@0.17.3
          node_modules/.bin/gren changelog --override

      - name: Commit files
        run: |
          git config --global user.email "hsh47607@naver.com"
          git config --global user.name "hseungho"
          git add CHANGELOG.md
          git commit -m "Update ChangeLog on ${{ matrix.ref }} branch"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ matrix.ref }}

  deploy-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/arm64/v8
            linux/arm/v7
            linux/ppc64le
            linux/s390x
            linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/workflowtest:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/workflowtest:${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
